version: 3.3

services:

	whoami:
		image: containous/whoami
		container_name: whoami
		labels:
			- traefik.enable=true
			- traefik.http.routers.whoami.rule=Host('whoami.ittotti.de')
      			- traefik.http.routers.whoami.entrypoints=websecure
      			- traefik.http.routers.whoami.tls.certresolver=defaultresolver
#			- traefik.docker.network=default
#			- traefik.docker.network=traefik_proxy
		networks:
#			- default
			- traefik_proxy
