## Static configuration

[entryPoints]
  [entryPoints.http]
    address = ":80"

  [entryPoints.https]
    address = ":443"

  [entryPoints.dashboard]
    address = ":8080"


[log]
  level = "DEBUG"


[providers]
  [providers.docker]
    exposedByDefault = false
    endpoint = "unix:///var/run/docker.sock"
    network = "traefik_proxy"
  [providers.file]
    filename = "/etc/traefik/dynamic.yml"
    

[api]
  dashboard = true
	entryPoint = "https"



[certificatesResolvers]
  [certificatesResolvers.default.acme]
    email = "reiner.petersen@posteo.de" #Email Adresse hier anpassen
    storage = "/etc/traefik/ACME/acme.json"
    [certificatesResolvers.default.acme.tlsChallenge]
