# https://github.com/portainer/portainer/issues/1542
# https://github.com/MatchbookLab/local-persist
# https://stackoverflow.com/questions/50733139/portainer-create-new-volume
# https://www.composerize.com/
# https://github.com/cagataygurturk/docker-ssh-tunnel

version: "2"

volumes:
    portainer_test_data:
    
services:
    portainer_test:
        ports:
#            - '8000:8000'
            - 19000:9000
        container_name: portainer_test
        restart: always
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - portainer_test_data:/data
        image: portainer/portainer
        
    autossh_portainer_agent:
        image: autossh_docker:latest
        container_name: ssh_portainer_agent
        volumes:
          - /etc/autossh/id_rsa:/root/ssh/id_rsa:ro
        environment:
          USER_HOST: vicke
          TUNNEL_HOST: mail.totti.to
          REMOTE_HOST: 172.18.0.2
          LOCAL_PORT: 9002
          REMOTE_PORT: 9001