version: '2'

services:
    duplicati:
        image: duplicati/duplicati
        ports:
            - '8200:8200'
        volumes:
            #   CONFIG
            - /ssd/duplicati/data:/data
            #   TARGET
            - /ssd/duplicati/bkp:/home/bkp
            #   SOURCES
            # - /home/icke/.config/appdata/portainer:/home/source/portainer
            - /var/lib/docker/volumes:/home/source/docker-volumes
            # - /ssd/nextcloud/data:/home/source/nextcloud/data