version: '2'

# volumes:
# #   CONFIG
    # duplicati-data:
# #   TARGET
    # bkp:
# #   SOURCES
    # portainer_portainer_data:
# #    etc:
    
services:
    duplicati:
        image: duplicati/duplicati
        ports:
            - '8200:8200'
        volumes:
            #   CONFIG
            - '/ssd/duplicati/data:/data'
            #   TARGET
            - '/ssd/duplicati/bkp:/home/bkp'
            #   SOURCES
            - '/home/icke/.config/appdata/portainer:/home/source/portainer'