# Use the appliance image for the fastest approach
# Modify agent-IP as given here https://techexpert.tips/zabbix/zabbix-docker-installation-ubuntu-linux/

version: "2"

services:

    zabbix:
        ports:
            - 1234:80
            - 12345:10051
        image: zabbix/zabbix-appliance:latest
        container_name: zabbix_main
        restart: unless-stopped

    zabbix_agent:
        container_name: zabbix-agent
        environment:
            - ZBX_HOSTNAME=zabbix-agent
            - ZBX_SERVER_HOST=172.1XX.XXX.XXX
        image: zabbix/zabbix-agent
        privileged: true
        restart: unless-stopped