#	LXQt
#	http://ubuntuhandbook.org/index.php/2017/04/custom-screen-resolution-ubuntu-desktop/

version: '2'

volumes:
	gua_db:
#  nc_web:  

services:
  db:
    image: mariadb
    restart: always
    volumes:
      - gua_db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=r4zouATZpdBzsBpafYKY
      - MYSQL_USER=gua
      - MYSQL_DATABASE=gua_db
      - MYSQL_PASSWORD=yBXmcn5bFrhhdOV1RhqX
  
  guacd:
	image: guacamole/guacd