version: 3.3

services:

  traefik:
    image: traefik:v2.2
    container_name: traefik
    ports:
      - 80:80
			- 443:443
		networks:
			- default
			- traefik_proxy
		volumes:
      - etc/letsencrypt:/letsencrypt
      - /var/run/docker.sock:/var/run/docker.sock:ro
			- /var/docker/traefik/config:/etc/traefik


