version: '2'

# volumes:
  # nc:         #   /ssd/nextcloud/server
  # nc_data:    #   /ssd/nextcloud/data
  # nc_db:      #   /ssd/nextcloud/mysql
  # nc_conf:    #   /ssd/nextcloud/config
  # nc_apps:    #   /ssd/nextcloud/apps
  # nc_web:     #   

services:
  db:
    image: mariadb
    restart: always
    container_name: nc_db
    volumes:
      - /ssd/nextcloud/mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=nextcloud
      - MYSQL_PASSWORD=nextcloud
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud

  app:
    image: nextcloud:19-fpm
    container_name: nc_app
   ports:
     - 38080:80
    links:
      - db
    volumes:
      - /ssd/nextcloud/server:/var/www/html/
      - /ssd/nextcloud/data:/var/www/html/data
      - /ssd/nextcloud/config:/var/www/html/config
      - /ssd/nextcloud/apps:/var/www/html/apps
    restart: always

  # web:
    # image: nginx
    # container_name: nc_nginx
    # ports:
      # - 38080:80
    # links:
      # - app
    # volumes:
      # # https://github.com/nextcloud/docker/blob/master/.examples/docker-compose/with-nginx-proxy/mariadb/fpm/web/nginx.conf
      # - /home/icke/test/nginx.conf:/etc/nginx/nginx.conf:ro
    # volumes_from:
      # - app
    # restart: always

####################
#   Backup Restore nach 
#   https://www.c-rieger.de/nextcloud-backup-and-restore/
#   https://hub.docker.com/_/nextcloud/
#   https://gist.github.com/nshtg/24c22f8878456e00c1f07f762038f58c
#####################
#   Restore MySQL-Database
#   Benutze das neue MySQL-Passwort!
#####################
#   cat /data_4TB/bkp/nc/ncdb_201226_1701.sql | docker exec -i nc_db /usr/bin/mysql -u nextcloud -ppassword nextcloud