version: "2"
services:
  wireguard:
    image: ghcr.io/linuxserver/wireguard
    container_name: wireguard
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Berlin
      - SERVERURL=domain.tld #optional
      - SERVERPORT=1234 #optional
      - PEERS=20 #optional
#      - PEERDNS=auto #optional
      - INTERNAL_SUBNET=10.10.10.0 #optional
      - ALLOWEDIPS=0.0.0.0/0 #optional
    volumes:
      - /home/icke/wireguard/config:/config
      - /lib/modules:/lib/modules
    ports:
      - 1234:51820/udp
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
    restart: unless-stopped